name: Release .NET Application AppA

on:
  workflow_dispatch

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Important to fetch all history for scripts calculating changes

    - name: Determine Changeset for AppA
      id: changeset
      run: |
        # Determine the last tag to compare changes from
        LAST_TAG=$(git describe --tags --abbrev=0)
        
        # List all changed files since the last tag, filtering by those in the App1 or Common directories
        CHANGED_FILES=$(git diff --name-only $LAST_TAG HEAD | grep -E "src/Test/AppA/|src/Test/Core/")
        echo "Changed Files: $CHANGED_FILES"
        
        # Check if the variable is empty or not
        if [[ -z "$CHANGED_FILES" ]]; then
          echo "APP1_AFFECTED=false" >> $GITHUB_ENV
        else
          echo "APP1_AFFECTED=true" >> $GITHUB_ENV
        fi
