name: Determine and Deploy Changed Applications

on:
  push:
    branches:
      - main
    paths:
      - src/Test/**

jobs:
  find-and-deploy-changed-apps:
    runs-on: ubuntu-latest
    outputs:
      changed-apps: ${{ steps.set-output.outputs.changed-apps }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 2  # Fetches the commit history to compare changes

    - name: Find changed applications
      id: set-output
      run: |
        # List changes comparing HEAD with the previous commit
        CHANGES=$(git diff --name-only HEAD^ HEAD | grep '^src/test/' | awk -F'/' '{print $3}' | sort -u)
        echo "Changed applications: $CHANGES"
        
        # Set the output variable to the list of changed apps
        echo "CHANGED_APPS=$CHANGES" >> $GITHUB_ENV

    - name: Deploy AppA
      if: contains(env.CHANGED_APPS, 'AppA') || contains(env.CHANGED_APPS, 'Core')
      run: |
        echo "Deploying AppA"

    - name: Deploy AppB
      if: contains(env.CHANGED_APPS, 'AppB') || contains(env.CHANGED_APPS, 'Core')
      run: |
        echo "Deploying AppB"
