name: Validate PR Changes

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
    paths:
      - 'src/**'

jobs:
  calculate-changed-files:
    name: Check what files have changes
    runs-on: ubuntu-latest
    outputs:
      core_changed: ${{ steps.filter.outputs.core }}
      appA_changed: ${{ steps.filter.outputs.appA }}
      appb_changed: ${{ steps.filter.outputs.appB }}
      # Repeat for other apps as needed
    steps:
      - uses: actions/checkout@v4
      
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            core:
              - 'src/Test/Core/**'
            appA:
              - 'src/Test/AppA/**'
            appB:
              - 'src/Test/AppB/**'
            # Repeat for other apps as needed

  validate-app-core:
    name: App Core
    needs: calculate-changed-files
    if: needs.calculate-changed-files.outputs.core_changed == 'true'
    uses: ./.github/workflows/action_validate_pr.yml
    with:
      APP_NAME: 'Core'
      PROJECT_NAME: 'Test.Core'
    secrets: inherit

  validate-app-appA:
    name: App AppA
    needs: calculate-changed-files
    if: needs.calculate-changed-files.outputs.appA_changed == 'true'
    uses: ./.github/workflows/action_validate_pr.yml
    with:
      APP_NAME: 'AppA'
      PROJECT_NAME: 'Test.Api.App.A'
    secrets: inherit

  validate-app-appB:
    name: App AppB
    needs: calculate-changed-files
    if: needs.calculate-changed-files.outputs.appB_changed == 'true'
    uses: ./.github/workflows/action_validate_pr.yml
    with:
      APP_NAME: 'AppB'
      PROJECT_NAME: 'Test.Api.App.B'
    secrets: inherit
