name: Build and Test Affected Applications

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    paths:
      - 'src/**'

jobs:
  changed-files:
    runs-on: ubuntu-latest
    outputs:
      core_changed: ${{ steps.filter.outputs.core_changed }}
      appA_changed: ${{ steps.filter.outputs.appA }}
      appb_changed: ${{ steps.filter.outputs.appB_changed }}
      # Repeat for other apps as needed
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            core:
              - 'src/Test/Core/**'
            appA:
              - 'src/Test/AppA/**'
            appB:
              - 'src/Test/AppB/**'
            # Repeat for other apps as needed

  build-and-test-core:
    needs: changed-files
    if: needs.changed-files.outputs.core_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.101' # Specify your .NET version
      - name: Build and Test Core
        run: |
          cd src\Test\Core\Test.Core
          dotnet build
          dotnet test

  build-and-test-appA:
    needs: changed-files
    if: >-
      needs.changed-files.outputs.core_changed == 'true' ||
      needs.changed-files.outputs.appA_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.101' # Adjust .NET version as needed
      
      - name: Build and Test AppA
        run: |
          cd src/Test/AppA/Test.Api.App.A
          dotnet build
          cd ..\tests\Test.Api.App.A.Tests
          dotnet test

      - name: Generate Release Notes
        id: generate-notes-appA
        run: |
          RELEASE_NOTES_APPA=""
          RELEASE_NOTES_APPA+="## AppA\n"
          RELEASE_NOTES_APPA+=$(git log --pretty=format:"- %s" $(git merge-base HEAD main)..HEAD -- src/Test/AppA/)
          RELEASE_NOTES_APPA+="\n\n"
          
          # Repeat for other applications as necessary
          
          echo "RELEASE_NOTES_APPA<<EOF" >> $GITHUB_ENV
          echo -e "$RELEASE_NOTES_APPA" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Append to CHANGELOG.md
        run: |
          NOTES="${{ env.RELEASE_NOTES_APPA }}"
          FILE="./src/Test/AppA/CHANGELOG.md"
          echo -e "## Release Notes - $(date +'%Y-%m-%d')\n\n$NOTES\n\n$(cat $FILE)" > $FILE

  build-and-test-appB:
    needs: changed-files
    if: >-
      needs.changed-files.outputs.core_changed == 'true' ||
      needs.changed-files.outputs.appB_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.101' # Adjust .NET version as needed
      - name: Build and Test AppB
        run: |
          cd src/Test/AppB/Test.Api.App.B
          dotnet build
          dotnet test
