name: Build and Test Affected Applications

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    paths:
      - 'src/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Necessary to compare changes against the main branch

      - name: Install .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.101' # Specify your .NET version here

      - name: Detect Changed Files
        id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'space-delimited'

      - name: Determine Affected Applications
        id: affected
        run: |
          CHANGED_FILES="${{ steps.files.outputs.all }}"
          AFFECTED_APPS=""
          for FILE in $CHANGED_FILES; do
            if [[ "$FILE" == src/AppA/* ]]; then
              AFFECTED_APPS+="AppA "
            elif [[ "$FILE" == src/AppB/* ]]; then
              AFFECTED_APPS+="AppB "
            elif [[ "$FILE" == src/Core/* ]]; then
              AFFECTED_APPS+="AppA AppB"
            fi
          done
          echo "AFFECTED_APPS=${AFFECTED_APPS}" >> $GITHUB_ENV

      - name: Build and Test Affected Applications
        if: env.AFFECTED_APPS != ''
        run: |
          for APP in $AFFECTED_APPS; do
            echo "Building and testing $APP"
            # Replace with your actual build and test commands
            dotnet build src/$APP
            dotnet test src/$APP
          done
